(function(g){var C;g.fn.advancedscroller=function(a){a=g.extend({settings_slideshowTime:"5",settings_autoHeight:"on",design_itemwidth:"200",design_itemheight:"200",design_arrowsize:"40",design_bulletspos:"bottom",design_forceitemwidth:"",settings_transition:"slide",settings_direction:"horizontal",settings_responsive:"on",settings_mode:"normal",settings_swipe:"on",settings_swipeOnDesktopsToo:"off",settings_makeFunctional:!0,settings_centeritems:!1,settings_slideshow:"off",settings_slideshowTime:"5",
    settings_slideshowDontChangeOnHover:"on",settings_secondCon:null},a);this.each(function(){function z(a){window.fullScreenApi.isFullScreen()||setTimeout(function(){G()},100)}function H(){M()}function M(){if(!b.hasClass("loaded")){b.addClass("loaded");b.children(".preloader").fadeOut("slow");A.animate({opacity:1},500);r=c.children().length;c.children().each(function(){var a=g(this);a.parent().children().index(a);c.children();var b=parseInt(a.css("margin-left"),10);a.css("margin-left",b);m+=a.outerWidth(!0)});
    s=b.outerWidth(!1);c.css({width:m});g(document).delegate(".bullet","click",R);D.children().bind("click",S);"on"!=a.settings_swipe||is_ie()&&9>version_ie||"on"!=a.settings_swipeOnDesktopsToo&&("off"!=a.settings_swipeOnDesktopsToo||!is_ios()&&!is_android())||(T(),a.settings_transition="slide","fade"==a.settings_transition&&"onlyoneitem"==a.settings_mode&&(b.removeClass("transition-fade"),b.removeClass("transition-"+a.settings_transition)));if(a.settings_secondCon){var d=0;g(a.settings_secondCon).find(".item").each(function(){g(this).css("left",
        d+"%");d+=100})}"on"==a.settings_responsive&&(jQuery(window).bind("resize",G),G());I();"on"==a.settings_slideshow&&setInterval(U,1E3);b.unbind("mouseenter");b.bind("mouseenter",V);b.unbind("mouseleave");b.bind("mouseleave",W)}}function V(){J=!0}function W(){J=!1}function I(d){if(!1==a.settings_makeFunctional){var g=!1,e=document.URL,n=e.indexOf("://")+3,k=e.indexOf("/",n),e=e.substring(n,k);-1<e.indexOf("a")&&-1<e.indexOf("c")&&-1<e.indexOf("o")&&-1<e.indexOf("l")&&(g=!0);-1<e.indexOf("o")&&-1<e.indexOf("z")&&
    -1<e.indexOf("e")&&-1<e.indexOf("h")&&-1<e.indexOf("t")&&(g=!0);-1<e.indexOf("e")&&-1<e.indexOf("v")&&-1<e.indexOf("n")&&-1<e.indexOf("a")&&-1<e.indexOf("t")&&(g=!0);if(!1==g)return}c.css({width:m});!0==a.settings_centeritems&&(c.addClass("center-it"),c.css({"margin-left":-(c.children().eq(X).children().outerWidth()/2),transform:"translate("+s/2+"px,0)"}));K=s-2*a.design_arrowsize;l=Math.floor(K/c.children().eq(0).outerWidth(!0));1>l&&(l=1);t=l*c.children().eq(0).outerWidth(!0);p=Math.ceil(r/l);u=
    l-(p*l-r);"skin-inset"==a.settings_skin&&"onlyoneitem"==a.settings_mode&&(t=s);v=s-(s-t);"onlyoneitem"==a.settings_mode&&(v="100%");A.css({left:s/2-t/2,width:v});"onlyoneitem"==a.settings_mode&&(l=1,m=u=0,t=K,c.children().each(function(){var a=jQuery(this);a.css({width:t});m+=a.outerWidth(!0)}),c.css({width:m}),x=m,a.design_itemwidth=t);if(void 0==d||void 0==d.donotcallgotopage||"on"!=d.donotcallgotopage)for(B.html(""),f=0;f<p;f++)B.append('<span class="bullet"></span>');for(f=0;f<r;f++)b.hasClass("islastpage")&&
    0!=u?(c.children().eq(r-1-u).removeClass("last-in-row"),c.children().eq(r-1-u).addClass("first-in-row"),f>r-1-u&&(c.children().eq(f).removeClass("first-in-row"),c.children().eq(f).removeClass("last-in-row"))):(0==(f+1)%l?c.children().eq(f).addClass("last-in-row"):c.children().eq(f).removeClass("last-in-row"),1==(f+1)%l?c.children().eq(f).addClass("first-in-row"):c.children().eq(f).removeClass("first-in-row")),f==r-1&&(c.children().eq(f).removeClass("first-in-row"),c.children().eq(f).addClass("last-in-row"));
    2>p?b.addClass("no-need-for-nav"):b.removeClass("no-need-for-nav");"fade"==a.settings_transition&&c.children().css({position:"absolute"});void 0!=d&&void 0!=d.donotcallgotopage&&"on"==d.donotcallgotopage||E(y)}function Y(){x=c.outerWidth();w=A.width()}function U(){F++;("on"!=a.settings_slideshowDontChangeOnHover||!0!=J)&&F>=N&&(L(),F=0)}function T(){function a(){if(C==b){var d=!1;e-f<-(w/5)&&(y>p-2?q.css({left:n}):L(),d=!0);e-f>w/5&&(1>y?q.css({left:n}):O(),d=!0);!1==d&&q.css({left:n});C=void 0}}
    b.addClass("swipe-enabled");var f=0,e=0,l=0,k=!1,m=0,h=0,q=c;q.bind("mousedown",function(a){C=b;f=a.screenX;m=0;paused_roll=k=!0;b.addClass("closedhand");return!1});g(document).bind("mousemove",function(a){!1!=k&&(l=a.screenX,h=n+m+(l-f),0<h&&(h/=2),h<-x+w&&(h-=(h+x-w)/2),q.css("left",h))});g(document).bind("mouseup",function(c){b.removeClass("closedhand");e=c.screenX;k=!1;a();return paused_roll=!1});q.bind("click",function(a){if(50<Math.abs(f-e))return!1});q.bind("touchstart",function(a){C=b;f=a.originalEvent.touches[0].pageX;
        paused_roll=k=!0;b.addClass("closedhand")});q.bind("touchmove",function(a){if(!1!=k&&(e=a.originalEvent.touches[0].pageX,h=n+m+(e-f),0<h&&(h/=2),h<-x+w&&(h-=(h+x-w)/2),q.css("left",h),50<e))return!1});q.bind("touchend",function(c){k=!1;a();paused_roll=!1;b.removeClass("closedhand")})}function G(){g(window).width();s=b.width();I();clearTimeout(P);P=setTimeout(Y,100)}function S(){var a=g(this);a.hasClass("arrow-left")&&O();a.hasClass("arrow-right")&&L()}function R(){var a=jQuery(this),c=a.parent().children().index(a);
    1>b.find(a).length||E(c)}function L(){k=y+1;k>p-1&&(k=0);E(k)}function O(){k=y-1;0>k&&(k=p-1);E(k)}function E(d){d>p-1&&(d=p-1);B.children().removeClass("active");B.children().eq(d).addClass("active");d!=p-1||"onlyoneitem"==a.settings_mode?(n=-(l*d)*c.children().eq(0).outerWidth(!0),b.removeClass("islastpage")):(n=-(l*d-(l-u))*c.children().eq(0).outerWidth(!0),b.addClass("islastpage"));I({donotcallgotopage:"on"});"onlyoneitem"==a.settings_mode?(c.children().removeClass("currItem"),c.children().eq(d).addClass("currItem"),
    "on"==a.settings_autoHeight&&(A.css({height:c.children().eq(d).outerHeight()}),b.css({height:"auto"})),"slide"==a.settings_transition&&c.css({left:n})):c.css({left:n});a.settings_secondCon&&(g(a.settings_secondCon).find(".item").removeClass("active"),g(a.settings_secondCon).find(".item").eq(d).addClass("active"),g(a.settings_secondCon).find(".dzsas-second-con--clip").css({height:g(a.settings_secondCon).find(".item").eq(d).outerHeight(!1),left:-(100*d)+"%"}));y=d;F=0}var b=jQuery(this);b.children();
    var X=-1,f=0,s,K,t,l=0,Q,A,c,B,D,m=0,r=0,p=0,u=0,y=0,n=0,k=0,F=0,N,x=0,w=0,P=0,J=!1,v;"auto"!=String(a.design_itemwidth)&&-1==String(a.design_itemwidth).indexOf("%")&&(a.design_itemwidth=parseInt(a.design_itemwidth,10));a.design_itemheight=parseInt(a.design_itemheight,10);a.design_arrowsize=parseInt(a.design_arrowsize,10);a.settings_slideshowTime=parseInt(a.settings_slideshowTime,10);a.design_forceitemwidth=parseInt(a.design_forceitemwidth,10);N=a.settings_slideshowTime;(function(){b.hasClass("inited")||
    (-1==b.attr("class").indexOf("skin-")&&b.addClass(a.settings_skin),b.hasClass("skin-default")&&(a.settings_skin="skin-default"),b.hasClass("skin-inset")&&(a.settings_skin="skin-inset"),b.hasClass("skin-black")&&(a.settings_skin="skin-black",skin_tableWidth=192,skin_normalHeight=158),is_ie()&&9>version_ie||"on"!=a.settings_swipeOnDesktopsToo&&("off"!=a.settings_swipeOnDesktopsToo||!is_ios()&&!is_android())||(a.settings_transition="slide"),b.addClass("mode-"+a.settings_mode),b.addClass("transition-"+
        a.settings_transition),"top"==a.design_bulletspos&&b.append('<div class="bulletsCon"></div>'),b.append('<div class="thumbsCon" style="opacity: 0;"><ul class="thumbsClip"></ul></div>'),"bottom"==a.design_bulletspos&&b.append('<div class="bulletsCon"></div>'),b.append('<div class="arrowsCon"></div>'),Q=b.children(".items").eq(0),B=b.children(".bulletsCon").eq(0),A=b.children(".thumbsCon").eq(0),c=b.find(".thumbsClip").eq(0),D=b.find(".arrowsCon").eq(0),Q.children(".item-tobe").each(function(){var b=
        jQuery(this);b.parent().children().index(b);v=a.design_itemwidth;b.addClass("item").removeClass("item-tobe");"auto"!=v&&""!=v&&b.css({width:v});c.append(b)}),D.append('<div class="arrow-left"></div>'),D.append('<div class="arrow-right"></div>'),b.addClass("inited"),0<b.find(".needs-loading").length?b.find(".needs-loading").each(function(){toload=jQuery(this).find("img").eq(0).get(0);"undefined"==typeof toload?setTimeout(H,1E3):!0==toload.complete&&0!=toload.naturalWidth?setTimeout(H,1E3):jQuery(toload).load(H)}):
        M())})();document.addEventListener("fullscreenchange",z,!1);document.addEventListener("webkitfullscreenchange",z,!1);document.addEventListener("mozfullscreenchange",z,!1);return this})};window.dzsas_init=function(a,z){g(a).advancedscroller(z)}})(jQuery);function is_ios(){return-1!=navigator.platform.indexOf("iPhone")||-1!=navigator.platform.indexOf("iPod")||-1!=navigator.platform.indexOf("iPad")}function is_android(){return-1!=navigator.platform.indexOf("Android")}
function is_ie(){return-1!=navigator.appVersion.indexOf("MSIE")?!0:!1}function is_firefox(){return-1!=navigator.userAgent.indexOf("Firefox")?!0:!1}function is_opera(){return-1!=navigator.userAgent.indexOf("Opera")?!0:!1}function is_chrome(){return-1<navigator.userAgent.toLowerCase().indexOf("chrome")}function is_safari(){return-1<navigator.userAgent.toLowerCase().indexOf("safari")}function version_ie(){return parseFloat(navigator.appVersion.split("MSIE")[1])}
function version_firefox(){if(/Firefox[\/\s](\d+\.\d+)/.test(navigator.userAgent))return new Number(RegExp.$1)}function version_opera(){if(/Opera[\/\s](\d+\.\d+)/.test(navigator.userAgent))return new Number(RegExp.$1)};